service: ""

provider:
  name: aws
  runtime: nodejs16.x
  stage: ${opt:stage, 'dev'}
  region: ap-northeast-1
  memorySize: 256
  timeout: 300

  iamRoleStatements: ${self:custom.config.IAM_ROLE_POLICY}

  deploymentBucket: ${self:custom.config.BUCKET}
  deploymentPrefix: ${self:custom.config.DEPLOYMENTBUCKETPREFIX}

  environment:
    BUCKET: ${self:custom.config.BUCKET}
    STAGE: ${self:provider.stage}
    TZ: "Asia/Bangkok"
    POSTGRESQL_CONNECTSTRING: ${self:custom.config.POSTGRESQL_CONNECTSTRING}
    NAME_SCHEMA: ${self:custom.config.NAME_SCHEMA}

    SENDER: ${self:custom.config.SENDER}
    SES_REGION: ${self:custom.config.SES_REGION}

  tags:
    PROJECT: ""
    ENVIRONMENT: ${self:provider.stage}
    DEVELOPER: ""
    VERSION: v1.0

package:
  excludeDevDependencies: true
  exclude:
    - node_modules/aws-sdk/**
functions:
  app:
    handler: index.handler
    description: ""
    memorySize: 256
    timeout: 30
    events:
      - http: ANY /
      - http: "ANY /{proxy+}"

  job:
    handler: job.handler
    description: ""
    memorySize: 3008
    timeout: 900
    events:
      - schedule:
          name: sync-Data-at-01_30-am-${self:provider.stage}
          description: Sync users at 10:30AM (TZ Asia/Bangkok UTC +7)
          rate: cron(30 3 * * ? *)
          enabled: true
          input: '{ "body": { "key": "${self:custom.JOB_KEYS.SYNC_DATA}" }, "headers": { "Content-Type": "application/json" } }'

custom:
  config: ${file(./serverless.env.yml):${self:provider.stage}}
  JOB_KEYS:
    SYNC_DATA: Sync.User.Data
  prune:
    automatic: true
    number: 3

plugins:
  - serverless-offline
  - serverless-prune-plugin
